// Generated by CoffeeScript 1.7.1
(function() {
  var client;

  client = {
    primus: null,
    term: null,
    testOpts: function() {
      return {
        url: "http://127.0.0.1:8223",
        cols: 140,
        rows: 19,
        parent: document.getElementById("terminal")
      };
    },
    openTerm: function(opts) {
      this.term = new Terminal({
        cols: opts.cols,
        rows: opts.rows,
        useStyle: true,
        screenKeys: true
      });
      this.term.open(opts.parent);
      return this.term.on("data", (function(_this) {
        return function(data) {
          if (_this.primus != null) {
            return _this.primus.write(data);
          }
        };
      })(this));
    },
    openConnection: function(opts) {
      if (this.primus != null) {
        this.primus.end();
      }
      this.primus = Primus.connect(opts.url);
      this.primus.on('data', (function(_this) {
        return function(data) {
          return _this.term.write(data);
        };
      })(this));
      return this.primus.on('open', (function(_this) {
        return function() {
          _this.term.reset();
          return _this.term.emit("data", "clear\n");
        };
      })(this));
    },
    open: function() {
      var opts;
      opts = this.testOpts();
      this.openTerm(opts);
      return this.openConnection(opts);
    }
  };

  client.open();

}).call(this);
