// Generated by CoffeeScript 1.7.1
(function() {
  var server;

  server = {
    term: null,
    buff: [],
    primus: null,
    testOpts: function() {
      return {
        cols: 140,
        rows: 19,
        cwd: './',
        pathname: "/console",
        transformer: "engine.io",
        timeout: false,
        port: 8223
      };
    },
    upTerm: function(opts) {
      var term_opts, _ref, _ref1, _ref2, _ref3;
      term_opts = {
        name: (_ref = require('fs').existsSync('/usr/share/terminfo/x/xterm-256color')) != null ? _ref : {
          'xterm-256color': 'xterm'
        },
        cols: (_ref1 = opts != null ? opts.cols : void 0) != null ? _ref1 : 140,
        rows: (_ref2 = opts != null ? opts.rows : void 0) != null ? _ref2 : 19,
        cwd: (_ref3 = opts != null ? opts.cwd : void 0) != null ? _ref3 : '/root/atspad'
      };
      return this.term = require('pty.js').fork('bash', ['--rcfile', '/root/.bashrc'], term_opts);
    },
    upServer: function(opts) {
      var _ref, _ref1, _ref2, _ref3;
      this.primus = require('primus').createServer({
        pathname: (_ref = opts != null ? opts.pathname : void 0) != null ? _ref : "/primus",
        transformer: (_ref1 = opts != null ? opts.transformer : void 0) != null ? _ref1 : "engine.io",
        timeout: (_ref2 = opts != null ? opts.timeout : void 0) != null ? _ref2 : 35000,
        port: (_ref3 = opts != null ? opts.port : void 0) != null ? _ref3 : 8023
      });
      this.primus.save("" + __dirname + "/primus.js");
      this.term.on("data", (function(_this) {
        return function(data) {
          if (_this.primus.connected === 0) {
            return _this.buff.push(data);
          } else {
            return _this.primus.write(data);
          }
        };
      })(this));
      return this.primus.on("connection", (function(_this) {
        return function(spark) {
          while (_this.buff.length) {
            _this.primus.write(_this.buff.shift());
          }
          return spark.on('data', function(data) {
            return _this.term.write(data);
          });
        };
      })(this));
    },
    up: function(opts) {
      opts = this.testOpts();
      this.upTerm(opts);
      return this.upServer(opts);
    }
  };

  server.up();

}).call(this);
